swagger: "2.0"
info:
  description: This is our REST API
  version: "1.0.0"
  title: JukeBike REST API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /status:
    get:
      operationId: "main.status"
      summary: "Returns status of JukeBike Player"
      responses:
        200:
          description: "Successful"
          schema:
            type: "array"
            items:
              properties:
                trackname:
                  type: "string"
  /play:
    post:
      operationId: "main.play"
      summary: "plays current track"
      responses:
        200:
          description: "Successful"
  /pause:
    post:
      operationId: "main.pause"
      summary: "pauses player"
      responses:
        200:
          description: "Successful"
  /nextTrack:
    post:
      operationId: "main.next_track"
      summary: "skips current track"
      responses:
        200:
          description: "Successful"
  /addTrack/{track_uri}:
    post:
      summary: "Adds track from uri to queue"
      operationId: "main.add_track"
      parameters:
      - name: "track_uri"
        in: "path"
        description: "Track uri"
        required: true
        type: "string"
      responses:
        405:
          description: "Invalid input"
  /playTrack/{track_uri}:
      post:
        summary: "Adds track from uri to queue"
        operationId: "main.play_track"
        parameters:
        - name: "track_uri"
          in: "path"
          description: "Track uri"
          required: true
          type: "string"
        responses:
          405:
            description: "Invalid input"
